### PR TITLE
update/complete russian translation

### PR DESCRIPTION
**Pull request by TicClickie**
\\:D/

P.S. It turned out that it was more complete than I thought; props to the previous translator.
P.P.S. Tell me if you want it in unicode codepoints rather than raw strings.

### CODE REVIEW

**Comment by devondragon** [comment]
@TicClickie you may need to do it unicode...  I pushed it to the beta site here and it doesn't look right, at least in my browser - https://beta.10minutemail.com/10MinuteMail/index.html

Can you check how it looks for you?

**Comment by devondragon** [comment]
Actually confirmed it needs to be escaped.  I am pushing that now to beta.

**Comment by devondragon** [comment]
Much better!

**Comment by TicClickie** [comment]
Woah, it really is a disaster, looks like the encoding is broken, but I am not sure on whose side. It *has*, however, been saved in UTF-8.

...

Wow, it works, yeah! All's well that ends well, then! I'll have a look and will probably fix a thing or two.

**Comment by TicClickie** [comment]
..Okay, I was smart enough to nuke my branch before your feedback, so it appears I have to create yet another pull request.

**Pull request merged**
